### PR TITLE
US NSF addendum

### PR DESCRIPTION
**Pull request by kimberlybrogers**
Since I accepted Mei's file for practice, thought I'd add another file here so someone else can practice too. This is the documentation for the US NSF addendum to the T-AP grant. Hopefully I am doing this right?

### CODE REVIEW

**Comment by jessehoey** [comment]
I really think we need to discuss this pull request .... I am not sure it contributes to the Canadian aspect of this collaboration ;)

**Comment by jessehoey** [comment]
Im just practicing of course ... somebody else leave a comment and then I will merge

**Comment by kimberlybrogers** [comment]
Haha! Feel free not to merge if we don't want this in the master file. Didn't have any other relevant files to contribute for this exercise ;)

**Comment by jessehoey** [comment]
I just checked with Donald Trump and he says its OK so I will merge now

**Comment by kimberlybrogers** [comment]
My thanks to the Donald.

**Pull request merged**
